name: release
on:
  push:
    tags:
      - v*

jobs:
  release-golang:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/goreleaser/goreleaser-cross-toolchains
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short
      - name: Build and push base images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "OSX_SDK=${{env.OSX_SDK}}"
            "OSX_SDK_SUM=${{env.OSX_SDK_SUM}}"
            "OSX_VERSION_MIN=${{env.OSX_VERSION_MIN}}"
            "OSX_CROSS_COMMIT=${{env.OSX_CROSS_COMMIT}}"
